version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: transport-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: stockholm_transport
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transport-app
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/stockholm_transport
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
  mongo_data:
